/**
 * src/services/attribution/resolveBridgeAttribution.ts
 *
 * Bridge Token MVP resolver. Answers exactly one question:
 * "did this outbound Bridge Event's target asset generate any VSTRK
 * events afterward?" Nothing more.
 *
 * Deliberately excludes (see BridgeToken_FirstTouchConstraint.md):
 *   - attribution time windows (2s / 30s / 5min cutoffs)
 *   - confidence scoring / competing-bridge suppression
 *   - session_id as an attribution key or "visit" boundary — session_id
 *     here is long-lived and supporting context only
 *   - Visitor ID, Journey ID, fingerprinting, IP matching, session merging
 *   - First Touch
 *
 * Cardinality: an asset can map to more than one video row (§11 of the
 * spec doc) — this resolver does NOT assume asset_id -> single video.
 * It fans out across every video row for the target asset.
 *
 * A single bridge_token can appear on multiple outbound Bridge Events
 * (same configured redirect, clicked more than once) — so resolution is
 * anchored on one specific events.id, matching the validation query's
 * `WHERE b.bridge_token = ... AND b.id = ...`. listBridgeEventsByToken()
 * is provided to enumerate the candidates when you only have the token.
 */

import { supabase } from '../../lib/supabase';

export interface BridgeEvent {
  id: string;
  bridgeToken: string;
  createdAt: string;
  sourceVideoId: string | null;
  sourceSessionId: string | null;
  targetAssetId: string | null;
}

export interface TargetEventResult {
  targetVideoId: string;
  targetVideoTitle: string | null;
  sessionId: string | null;
  eventType: string;
  createdAt: string;
  secondsAfterBridge: number;
}

export interface BridgeAttributionResult {
  bridgeEvent: BridgeEvent;
  targetEvents: TargetEventResult[];
}

/**
 * All outbound Bridge Events sharing a given bridge_token, oldest first.
 * Use when you only have the token (e.g. from redirect_links.bridge_token)
 * and need to pick which specific click to resolve.
 */
export async function listBridgeEventsByToken(
  bridgeToken: string
): Promise<BridgeEvent[]> {
  const { data, error } = await supabase
    .from('events')
    .select('id, bridge_token, created_at, video_id, session_id, asset_id')
    .eq('bridge_token', bridgeToken)
    .order('created_at', { ascending: true });

  if (error || !data) return [];

  return data.map((row) => ({
    id: row.id,
    bridgeToken: row.bridge_token,
    createdAt: row.created_at,
    sourceVideoId: row.video_id,
    sourceSessionId: row.session_id,
    targetAssetId: row.asset_id,
  }));
}

/**
 * Resolves one specific Bridge Event (by events.id) to every subsequent
 * VSTRK event generated by its target asset's video(s).
 *
 * Mirrors this validation query exactly:
 *
 *   SELECT ... FROM events b
 *   JOIN videos v ON v.asset_id = b.asset_id
 *   JOIN events e ON e.video_id = v.id AND e.created_at > b.created_at
 *   WHERE b.bridge_token = ? AND b.id = ?
 *   ORDER BY e.created_at ASC
 */
export async function resolveBridgeAttribution(
  bridgeEventId: string
): Promise<BridgeAttributionResult | null> {
  // 1. Load the anchor Bridge Event.
  const { data: bridgeRow, error: bridgeErr } = await supabase
    .from('events')
    .select('id, bridge_token, created_at, video_id, session_id, asset_id')
    .eq('id', bridgeEventId)
    .maybeSingle();

  if (bridgeErr || !bridgeRow) return null;

  const bridgeEvent: BridgeEvent = {
    id: bridgeRow.id,
    bridgeToken: bridgeRow.bridge_token,
    createdAt: bridgeRow.created_at,
    sourceVideoId: bridgeRow.video_id,
    sourceSessionId: bridgeRow.session_id,
    targetAssetId: bridgeRow.asset_id,
  };

  if (!bridgeEvent.targetAssetId) {
    // Not an asset-promotion redirect — nothing to resolve.
    return { bridgeEvent, targetEvents: [] };
  }

  // 2. Target asset -> every video row for it (never assume exactly one).
  const { data: targetVideos, error: videosErr } = await supabase
    .from('videos')
    .select('id, video_title')
    .eq('asset_id', bridgeEvent.targetAssetId);

  if (videosErr || !targetVideos || targetVideos.length === 0) {
    return { bridgeEvent, targetEvents: [] };
  }

  const videoTitleById = new Map(targetVideos.map((v) => [v.id, v.video_title as string | null]));
  const targetVideoIds = targetVideos.map((v) => v.id);

  // 3. Every event on any of those videos, strictly after the bridge.
  const { data: laterEvents, error: laterErr } = await supabase
    .from('events')
    .select('video_id, session_id, event_type, created_at')
    .in('video_id', targetVideoIds)
    .gt('created_at', bridgeEvent.createdAt)
    .order('created_at', { ascending: true });

  if (laterErr || !laterEvents) {
    return { bridgeEvent, targetEvents: [] };
  }

  const bridgeTime = new Date(bridgeEvent.createdAt).getTime();

  const targetEvents: TargetEventResult[] = laterEvents.map((e) => ({
    targetVideoId: e.video_id,
    targetVideoTitle: videoTitleById.get(e.video_id) ?? null,
    sessionId: e.session_id,
    eventType: e.event_type,
    createdAt: e.created_at,
    secondsAfterBridge: (new Date(e.created_at).getTime() - bridgeTime) / 1000,
  }));

  return { bridgeEvent, targetEvents };
}